# Generated by Django 5.1.1 on 2025-01-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_is_deleted_subcategory_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belongings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=250)),
                ('purchase_date', models.DateField()),
                ('item_area', models.CharField(max_length=150)),
                ('damage_level', models.IntegerField()),
                ('favorite_level', models.IntegerField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
    ]
