# Generated by Django 5.1.1 on 2025-02-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_belongings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belonging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='belongings_images/')),
                ('purchase_date', models.DateField()),
                ('item_area', models.CharField(max_length=150)),
                ('damage_level', models.IntegerField(choices=[(1, '軽い損傷'), (2, 'やや軽い損傷'), (3, '中程度の損傷'), (4, 'やや重い損傷'), (5, '重い損傷')])),
                ('favorite_level', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_in_decluttering', models.BooleanField(default=False)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Belongings',
        ),
    ]
